import { Submissions, Submission } from '../models/submissions'

export const sample_submission: Submissions = {
  '147': {
    '38128': {
      _id: '38128',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2019-09-18T20:00:00Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: false,
      rubric: {
        '5171_2499': {
          comments: 'AE. Scientific explanation made a claim that is supported by the NaCl part of the data, but the claim was not supported by the glucose part of the data.  You did a good job using data as evidence for the NaCl part.  ',
          points: 2
        },
        '5171_2585': {
          comments: 'AE+. Drew particle model diagrams that accurately modeled particle type and phase of matter, but not concentration (the number of water molecules should remain constant).',
          points: 2
        },
        '5171_9062': {
          comments: 'AE+. Drew particle model diagrams that accurately modeled particle type and phase of matter, but not concentration (the number of water molecules should remain constant).',
          points: 2
        },
        _3771: {
          comments: 'AE+. Drew a clear  graph but was missing axis labels and units.  Analyzed the graphical and tabular data to identify relationships and to make a valid claim about concentration and conductivity for NaCl but not for glucose.',
          points: 2.5
        },
        _398: {
          comments: 'No questions or curiosity noted in your notebook during this investigation.',
          points: null
        }
      },
      score: 0,
      student_id: '147',
      submitted_at: null
    }
  },
  '4321': {
    '34146': {
      _id: '34146',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-09T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '35736': {
      _id: '35736',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-11T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '37112': {
      _id: '37112',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-17T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38020': {
      _id: '38020',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2019-09-24T17:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38021': {
      _id: '38021',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-19T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38022': {
      _id: '38022',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2019-09-24T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38128': {
      _id: '38128',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-18T20:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38624': {
      _id: '38624',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-25T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38709': {
      _id: '38709',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-27T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '38980': {
      _id: '38980',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-09-25T19:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39038': {
      _id: '39038',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-03T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39039': {
      _id: '39039',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: null,
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39277': {
      _id: '39277',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-11T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39278': {
      _id: '39278',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2019-10-11T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39300': {
      _id: '39300',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-08T00:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39724': {
      _id: '39724',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-15T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '39862': {
      _id: '39862',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-17T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40182': {
      _id: '40182',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-23T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40183': {
      _id: '40183',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-23T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40291': {
      _id: '40291',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-25T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40329': {
      _id: '40329',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-25T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40392': {
      _id: '40392',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2019-11-26T21:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40639': {
      _id: '40639',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-10-29T19:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '40854': {
      _id: '40854',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-11-04T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '41168': {
      _id: '41168',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-11-06T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '41400': {
      _id: '41400',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-11-12T21:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '42089': {
      _id: '42089',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-11-22T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '42635': {
      _id: '42635',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-12-04T15:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '42693': {
      _id: '42693',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-12-06T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '42993': {
      _id: '42993',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2019-12-12T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '43754': {
      _id: '43754',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-08T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '43892': {
      _id: '43892',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-13T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '43972': {
      _id: '43972',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-13T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44076': {
      _id: '44076',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-15T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44486': {
      _id: '44486',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-23T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44487': {
      _id: '44487',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-17T20:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44731': {
      _id: '44731',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-29T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44776': {
      _id: '44776',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-28T04:59:59Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44868': {
      _id: '44868',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-31T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '44937': {
      _id: '44937',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-31T20:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '45092': {
      _id: '45092',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-01-29T20:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '45400': {
      _id: '45400',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-02-10T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '45878': {
      _id: '45878',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-02-19T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '46029': {
      _id: '46029',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-02-24T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '46284': {
      _id: '46284',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-02-28T13:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '46603': {
      _id: '46603',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-03-05T13:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '46647': {
      _id: '46647',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-03-03T20:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '46739': {
      _id: '46739',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-03-11T12:30:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '46970': {
      _id: '46970',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-03-09T19:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '47211': {
      _id: '47211',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2020-04-04T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '47542': {
      _id: '47542',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2020-04-08T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '47544': {
      _id: '47544',
      assignment_visible: false,
      comments: [
        {
          author_name: 'Joe Test',
          comment: 'comment on submission 1',
          updatedAt: '2020-05-11T17:01:09Z'
        },
        {
          author_name: 'Joe Test',
          comment: 'second submission',
          updatedAt: '2020-05-11T17:39:14Z'
        }
      ],
      complete: false,
      dueAt: '2020-04-14T03:59:59Z',
      excused: false,
      grade: 'incomplete',
      gradedAt: null,
      late: true,
      missing: false,
      rubric: {
        _1353: {
          comments: 'A xxxxAdvanced....!',
          points: 3
        },
        _1780: {
          comments: 'P+ Better than proficient but not quite advanced....',
          points: 2.5
        },
        _4838: {
          comments: 'P Proficient....',
          points: 2
        },
        _5495: {
          comments: 'D Developing....',
          points: 1
        },
        _7365: {
          comments: 'NY Not yet.... ',
          points: 0
        }
      },
      score: 0,
      student_id: '4321',
      submitted_at: '2020-05-11T17:39:14Z'
    },
    '48149': {
      _id: '48149',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2020-04-16T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '48150': {
      _id: '48150',
      assignment_visible: false,
      comments: [
        {
          author_name: 'Steven',
          comment: 'submission comment comment comment',
          updatedAt: '2020-05-06T20:17:19Z'
        }
      ],
      complete: true,
      dueAt: '2020-04-18T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: false,
      rubric: {
        '6883_1846': {
          comments: 'ME+\nPoster and video clearly and accurately explain with no errors errors or misconceptions... \n+ how sound waves are transmitted by oscillating objects\n+ how sound waves travel through oscillations of air molecules\n+ how sound waves are received by causing the oscillation of tiny objects\n+ how properties of sound like amplitude and frequency are related to the oscillation of particles',
          points: 3.5
        },
        '6883_1937': {
          comments: 'EE\n+ Poster and video show that you did additional research into sound.\n+ Asked good clarification and curiosity questions in the discussion.',
          points: 4
        },
        '6883_5852': {
          comments: 'ME\n+ Poster uses particle diagrams to accurately model the oscillation of air molecules.\n∆ Oscillations are more regular and less random.  It would be better to show the oscillation with arrows like this <--O-->, rather than ""O""\n',
          points: 3.5
        }
      },
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '48731': {
      _id: '48731',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2020-04-27T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '48942': {
      _id: '48942',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-05-02T03:59:59Z',
      excused: false,
      grade: 'incomplete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '49443': {
      _id: '49443',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-05-08T13:00:00Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '49634': {
      _id: '49634',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-05-09T03:59:59Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '49804': {
      _id: '49804',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2020-05-13T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '49975': {
      _id: '49975',
      assignment_visible: false,
      comments: [],
      complete: true,
      dueAt: '2020-05-16T03:59:59Z',
      excused: false,
      grade: 'complete',
      gradedAt: null,
      late: false,
      missing: true,
      score: 0,
      student_id: '4321',
      submitted_at: null
    },
    '49976': {
      _id: '49976',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-05-21T03:59:59Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '50165': {
      _id: '50165',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-05-20T03:59:59Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '50293': {
      _id: '50293',
      assignment_visible: false,
      comments: [],
      complete: false,
      dueAt: '2020-05-23T03:59:59Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: true,
      score: null,
      student_id: '4321',
      submitted_at: null
    },
    '50321': {
      _id: '50321',
      assignment_visible: false,
      comments: [],
      complete: null,
      dueAt: '2020-05-27T03:59:59Z',
      excused: null,
      grade: null,
      gradedAt: null,
      late: false,
      missing: false,
      score: null,
      student_id: '4321',
      submitted_at: null
    }
  }
}